import {
	RiPhoneFill,
	RiTruckFill,
	RiBillLine,
	RiDeleteBin2Fill,
} from 'react-icons/ri'
import {
	MdEmail,
	MdGroups,
	MdPendingActions,
	MdCancelScheduleSend,
} from 'react-icons/md'
import {
	BsHandbagFill,
	BsFillSuitHeartFill,
	BsShieldShaded,
	BsReplyFill,
	BsCartPlus,
	BsFillCartCheckFill,
	BsFillCartPlusFill,
	BsChatRightTextFill,
	BsCheckAll,
} from 'react-icons/bs'
import { FaUserCircle, FaTty } from 'react-icons/fa'
import {
	AiFillHome,
	AiFillStar,
	AiOutlineStar,
	AiFillEye,
	AiOutlineMenu,
	AiOutlineLogout,
	AiFillGift,
	AiOutlineDown,
	AiOutlineDashboard,
	AiOutlineCaretDown,
	AiOutlineCaretRight,
	AiFillCloseCircle,
	AiOutlineUpload,
	AiOutlineCloseCircle,
	AiOutlineUnorderedList,
	AiOutlineSearch,
	AiOutlineRollback,
} from 'react-icons/ai'
import {
	IoIosArrowForward,
	IoMdCreate,
	IoIosAdd,
	IoIosStats,
} from 'react-icons/io'
import {
	BiDotsHorizontalRounded,
	BiEdit,
	BiTrash,
	BiCustomize,
	BiSolidPencil,
	BiBadgeCheck,
} from 'react-icons/bi'
import { TbBrandProducthunt, TbDoorExit, TbRun } from 'react-icons/tb'
import { ImBin } from 'react-icons/im'
import { GrFormAdd, GrCompliance } from 'react-icons/gr'
import { TfiImport } from 'react-icons/tfi'

const icons = {
	RiPhoneFill,
	MdEmail,
	BsHandbagFill,
	FaUserCircle,
	AiFillHome,
	AiFillStar,
	AiOutlineStar,
	AiFillEye,
	AiOutlineMenu,
	BsFillSuitHeartFill,
	IoIosArrowForward,
	AiOutlineLogout,
	BsShieldShaded,
	RiTruckFill,
	AiFillGift,
	BsReplyFill,
	FaTty,
	AiOutlineDown,
	BiDotsHorizontalRounded,
	AiOutlineDashboard,
	MdGroups,
	TbBrandProducthunt,
	RiBillLine,
	AiOutlineCaretDown,
	AiOutlineCaretRight,
	RiDeleteBin2Fill,
	BiEdit,
	BiTrash,
	BiCustomize,
	BsCartPlus,
	BsFillCartCheckFill,
	BsFillCartPlusFill,
	AiFillCloseCircle,
	ImBin,
	AiOutlineUpload,
	AiOutlineCloseCircle,
	IoMdCreate,
	AiOutlineUnorderedList,
	TbDoorExit,
	AiOutlineSearch,
	GrFormAdd,
	IoIosAdd,
	BiSolidPencil,
	AiOutlineRollback,
	TfiImport,
	BsChatRightTextFill,
	IoIosStats,
	MdPendingActions,
	BsCheckAll,
	TbRun,
	GrCompliance,
	MdCancelScheduleSend,
	BiBadgeCheck,
}

export default icons
